config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, only: [:new, :create, :edit, :update, :index]
  end

  resources :songs, only: [:show, :index, :destroy]
  resources :playlists, only: [:index, :new, :create, :show, :edit, :update]

  root to: "artists#index"
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :artist

  scope :sorted_by_title, -> { order(title: :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.delete
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update]

  def index
    @playlists = Playlist.all
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)

    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist, only: [:index, :new, :create, :edit]
  before_action :set_song, only: [:show, :update, :destroy]

  def index
    if @artist.present?
      @songs = @artist.songs.all
    else
      @songs = Song.all
    end
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @song = @artist.songs.find(params[:id])
  end

  def update
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    @song.delete
    redirect_to request.referer
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end

  def set_artist
    @artist = Artist.find(params[:artist_id]) unless params[:artist_id].nil?
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render partial: 'form' %>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, artist_path(artist) %>
    </li>
  <% end %>
</ul>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: 'form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>

<%= link_to 'Edit', edit_artist_path(@artist) %>
<%= link_to 'Delete', artist_path(@artist), method: :delete %>
<%= link_to 'New Song', new_artist_song_path(@artist) %>
<%= link_to 'View Songs', artist_songs_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <%= f.text_field :name %>

  <% Song.all.each do |song| %>
    <div>
      <% if @playlist.songs.find_by(title: song.title) %>
        <%= check_box_tag(:song_ids, song.id, true, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <% else %>
        <%= check_box_tag(:song_ids, song.id, false, :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <% end %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit a Playlist</h1>

<%= render partial: 'form' %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>

<ul>
  <% @playlists.each do |playlist| %>
    <li>
      <%= link_to playlist.name, playlist_path(playlist) %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render partial: 'form' %>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>

<ul>
  <% @playlist.songs.each do |song| %>
    <li>
      <%= link_to song.title, song %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_playlist_path(@playlist) %>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>
  <% if @song.errors.any? %>
    <h2><%= pluralize(@song.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit a Song</h1>
<p>
  Edit <%= @song.title %> for <%= @artist.name %>
</p>

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<ul>
  <% @songs.sorted_by_title.each do |song| %>
    <li id='song_id_<%= song.id.to_s %>'>
      <%= link_to song.title, song_path(song) %>
      <span><em>(<%= link_to 'Delete', song_path(song), method: :delete %>)</em></span>
    </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>
  Add a new song for <%= @artist.name %>
</p>

<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= link_to @song.artist.name, artist_path(@song.artist) %>
<%= link_to 'Edit', edit_artist_song_path(@song.artist, @song) %>